version: '3.8'
services:
  ap:
    build: .
    command: bin/rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    environment:
      - 'HOST=449500f88b21.ngrok.io' # ngrokで生成された値に変える
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=dev_db'
    volumes:
      - datadir:/var/lib/mysql
volumes:
  bundle:
  datadir:
